
import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Theme = 'light' | 'dark';
type UISize = 'small' | 'medium' | 'large';
export type Language = 'en' | 'es' | 'fr' | 'zh' | 'ja' | 'ko';

interface ThemeContextType {
  theme: Theme;
  uiSize: UISize;
  snapEnabled: boolean;
  language: Language;
  autoHideControls: boolean;
  autoHideDuration: number;
  toggleTheme: () => void;
  setUiSize: (size: UISize) => void;
  toggleSnap: () => void;
  setLanguage: (lang: Language) => void;
  toggleAutoHide: () => void;
  setAutoHideDuration: (ms: number) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.save": "Save",
    "common.back": "Back",
    "common.today": "Today",
    "common.tomorrow": "Tomorrow",
    "common.add": "Add",
    "common.light_mode": "Light Mode",
    "common.dark_mode": "Dark Mode",
    "nav.list": "List",
    "nav.calendar": "Calendar",
    "nav.map": "Map",
    "nav.focus": "Focus",
    "nav.settings": "Settings",
    "nav.profile": "Profile",
    "nav.sync_local": "Local",
    "nav.sync_syncing": "Syncing",
    "nav.sync_saved": "Saved",
    "nav.sync_error": "Error",
    "nav.sync_synced": "Synced",
    "dashboard.title": "Task List",
    "dashboard.subtitle": "Active & Pending",
    "dashboard.active": "Active",
    "dashboard.today_section": "Today's Focus",
    "dashboard.upcoming": "Inbox & Upcoming",
    "dashboard.done": "Done",
    "dashboard.no_active": "No active tasks.",
    "dashboard.all_done": "All caught up!",
    "dashboard.all_done_desc": "You've completed everything scheduled for today.",
    "smartadd.placeholder": "Add a new task...",
    "smartadd.description": "Description (optional)",
    "smartadd.add_task": "Add Task",
    "calendar.no_tasks": "No tasks for this day.",
    "calendar.quick_add": "Add a task...",
    "task.checklist": "Checklist",
    "task.no_subtasks": "No subtasks yet.",
    "task.add_step": "Add Step",
    "task.add_item": "Add item",
    "task.add_new_step": "Add new step...",
    "task.edit_details": "Edit Details",
    "task.edit_title": "Edit Task",
    "task.name": "Task Name",
    "task.description": "Description",
    "task.subtasks": "Subtareas",
    "task.due_date": "Due Date",
    "task.importance": "Importance",
    "task.priority": "Priority",
    "task.important": "Important",
    "task.placeholder": "Task...",
    "timer.count": "Count",
    "timer.timer": "Timer",
    "timer.focusing": "Focusing...",
    "timer.recording": "Recording",
    "timer.ready": "Ready",
    "timer.stats": "Stats",
    "timer.daily_stats": "Today",
    "timer.total_sessions": "Total Sessions",
    "timer.roll_dice": "Roll Dice",
    "timer.rolling": "Rolling...",
    "journal.quick_notes": "Quick Notes",
    "journal.no_notes": "No notes yet",
    "journal.title": "Journal",
    "journal.search": "Search notes...",
    "journal.not_found": "No notes found.",
    "journal.unsaved": "Unsaved changes...",
    "journal.saved": "Saved",
    "journal.title_placeholder": "Note Title",
    "journal.content_placeholder": "Start writing...",
    "journal.select": "Select a note to view",
    "journal.create_prompt": "or create a new entry",
    "profile.title": "Profile & Account",
    "profile.cloud_sync": "Cloud Sync",
    "profile.synced": "Active & Synced",
    "profile.local": "Inactive (Local Mode)",
    "profile.auth_error": "Authentication Error",
    "profile.sign_out": "Sign Out",
    "profile.create_account": "Create Account",
    "profile.sign_in": "Sign In to Sync",
    "profile.google": "Google",
    "profile.or_email": "OR EMAIL",
    "profile.email_placeholder": "Email address",
    "profile.password_placeholder": "Password",
    "profile.sign_up": "Sign Up",
    "profile.have_account": "Already have an account? Sign In",
    "profile.no_account": "Don't have an account? Sign Up",
    "profile.exit_hub": "Exit to App Hub",
    "profile.upgrade": "Upgrade",
    "profile.plan_free": "Barista Plan (Free)",
    "profile.plan_pro": "Connoisseur Plan",
    "profile.plan_active": "Active",
    "profile.plan_upgrade_hint": "Upgrade for Cloud Sync",
    "hub.welcome": "Welcome to your Suite",
    "hub.subtitle": "Select an application to launch.",
    "hub.app.focus": "Daily planner, focus timer & journal.",
    "hub.app.brainstorm": "Canvas for ideas and mind maps.",
    "hub.app.vault": "Secure digital locker for assets.",
    "hub.app.tools": "Dice, Spinner, Coin Flip & more.",
    "hub.soon": "Soon",
    "settings.title": "Settings",
    "settings.theme": "Theme",
    "settings.language": "Language",
    "settings.map_interface": "Map & Interface",
    "settings.text_size": "Text & UI Size",
    "settings.snap": "Window Snapping",
    "settings.snap_desc": "Automatically snap windows to edges when dragging.",
    "settings.autohide": "Auto-Hide Controls",
    "settings.autohide_desc": "Hide map controls when idle.",
    "map.zoom_in": "Zoom In",
    "map.zoom_out": "Zoom Out",
    "map.reset": "Reset View",
    "map.arrange": "Arrange Windows",
    "map.hide_controls": "Hide Controls"
  },
  es: {
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.save": "Guardar",
    "common.back": "Atrás",
    "common.today": "Hoy",
    "common.tomorrow": "Mañana",
    "common.add": "Añadir",
    "common.light_mode": "Modo Claro",
    "common.dark_mode": "Modo Oscuro",
    "nav.list": "Lista",
    "nav.calendar": "Calendario",
    "nav.map": "Mapa",
    "nav.focus": "Enfoque",
    "nav.settings": "Ajustes",
    "nav.profile": "Perfil",
    "nav.sync_local": "Local",
    "nav.sync_syncing": "Sincronizando",
    "nav.sync_saved": "Guardado",
    "nav.sync_error": "Error",
    "nav.sync_synced": "Sincronizado",
    "dashboard.title": "Lista de Tareas",
    "dashboard.subtitle": "Activas y Pendientes",
    "dashboard.active": "Activas",
    "dashboard.today_section": "Enfoque de Hoy",
    "dashboard.upcoming": "Buzón y Próximos",
    "dashboard.done": "Completadas",
    "dashboard.no_active": "No hay tareas activas.",
    "dashboard.all_done": "¡Todo al día!",
    "dashboard.all_done_desc": "Has completado todo lo programado para hoy.",
    "smartadd.placeholder": "Añadir nueva tarea...",
    "smartadd.description": "Descripción (opcional)",
    "smartadd.add_task": "Añadir Tarea",
    "calendar.no_tasks": "No hay tareas para este día.",
    "calendar.quick_add": "Añadir tarea...",
    "task.checklist": "Lista de control",
    "task.no_subtasks": "Sin subtareas.",
    "task.add_step": "Añadir Paso",
    "task.add_item": "Añadir ítem",
    "task.add_new_step": "Añadir nuevo paso...",
    "task.edit_details": "Editar Detalles",
    "task.edit_title": "Editar Tarea",
    "task.name": "Nombre de Tarea",
    "task.description": "Descripción",
    "task.subtasks": "Subtareas",
    "task.due_date": "Fecha de Vencimiento",
    "task.importance": "Importancia",
    "task.priority": "Prioridad",
    "task.important": "Importante",
    "task.placeholder": "Tarea...",
    "timer.count": "Cronómetro",
    "timer.timer": "Temporizador",
    "timer.focusing": "Enfocando...",
    "timer.recording": "Grabando",
    "timer.ready": "Listo",
    "timer.stats": "Estadísticas",
    "timer.daily_stats": "Hoy",
    "timer.total_sessions": "Sesiones Totales",
    "timer.roll_dice": "Lanzar Dados",
    "timer.rolling": "Lanzando...",
    "journal.quick_notes": "Notas Rápidas",
    "journal.no_notes": "No hay notas aún",
    "journal.title": "Diario",
    "journal.search": "Buscar notas...",
    "journal.not_found": "No se encontraron notas.",
    "journal.unsaved": "Cambios sin guardar...",
    "journal.saved": "Guardado",
    "journal.title_placeholder": "Título de la Nota",
    "journal.content_placeholder": "Empieza a escribir...",
    "journal.select": "Selecciona una nota para ver",
    "journal.create_prompt": "o crea una nueva entrada",
    "profile.title": "Perfil y Cuenta",
    "profile.cloud_sync": "Sincronización en Nube",
    "profile.synced": "Activo y Sincronizado",
    "profile.local": "Inactivo (Modo Local)",
    "profile.auth_error": "Error de Autenticación",
    "profile.sign_out": "Cerrar Sesión",
    "profile.create_account": "Crear Cuenta",
    "profile.sign_in": "Iniciar Sesión para Sincronizar",
    "profile.google": "Google",
    "profile.or_email": "O EMAIL",
    "profile.email_placeholder": "Dirección de correo",
    "profile.password_placeholder": "Contraseña",
    "profile.sign_up": "Registrarse",
    "profile.have_account": "¿Ya tienes cuenta? Inicia Sesión",
    "profile.no_account": "¿No tienes cuenta? Regístrate",
    "profile.exit_hub": "Salir al Hub",
    "profile.upgrade": "Mejorar",
    "profile.plan_free": "Plan Barista (Gratis)",
    "profile.plan_pro": "Plan Connoisseur",
    "profile.plan_active": "Activo",
    "profile.plan_upgrade_hint": "Mejora para Sincronización en Nube",
    "hub.welcome": "Bienvenido a tu Suite",
    "hub.subtitle": "Selecciona una aplicación para iniciar.",
    "hub.app.focus": "Planificador diario, temporizador y diario.",
    "hub.app.brainstorm": "Lienzo para ideas y mapas mentales.",
    "hub.app.vault": "Casillero digital seguro para activos.",
    "hub.app.tools": "Dados, Ruleta, Moneda y más.",
    "hub.soon": "Pronto",
    "settings.title": "Configuración",
    "settings.theme": "Tema",
    "settings.language": "Idioma",
    "settings.map_interface": "Mapa e Interfaz",
    "settings.text_size": "Texto y Tamaño UI",
    "settings.snap": "Ajuste de Ventanas",
    "settings.snap_desc": "Ajustar ventanas automáticamente al arrastrar.",
    "settings.autohide": "Ocultar Controles",
    "settings.autohide_desc": "Ocultar controles del mapa al estar inactivo.",
    "map.zoom_in": "Acercar",
    "map.zoom_out": "Alejar",
    "map.reset": "Restablecer Vista",
    "map.arrange": "Organizar Ventanas",
    "map.hide_controls": "Ocultar Controles"
  },
  fr: {
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.save": "Enregistrer",
    "common.back": "Retour",
    "common.today": "Aujourd'hui",
    "common.tomorrow": "Demain",
    "common.add": "Ajouter",
    "common.light_mode": "Mode Clair",
    "common.dark_mode": "Mode Sombre",
    "nav.list": "Liste",
    "nav.calendar": "Calendrier",
    "nav.map": "Carte",
    "nav.focus": "Focus",
    "nav.settings": "Paramètres",
    "nav.profile": "Profil",
    "nav.sync_local": "Local",
    "nav.sync_syncing": "Sync...",
    "nav.sync_saved": "Enregistré",
    "nav.sync_error": "Erreur",
    "nav.sync_synced": "Synchronisé",
    "dashboard.title": "Liste des Tâches",
    "dashboard.subtitle": "Actives et En attente",
    "dashboard.active": "Actives",
    "dashboard.today_section": "Focus du Jour",
    "dashboard.upcoming": "Boîte de réception & À venir",
    "dashboard.done": "Terminées",
    "dashboard.no_active": "Aucune tâche active.",
    "dashboard.all_done": "Tout est à jour !",
    "dashboard.all_done_desc": "Vous avez terminé tout ce qui était prévu pour aujourd'hui.",
    "smartadd.placeholder": "Ajouter une nouvelle tâche...",
    "smartadd.description": "Description (optionnel)",
    "smartadd.add_task": "Ajouter Tâche",
    "calendar.no_tasks": "Aucune tâche pour ce jour.",
    "calendar.quick_add": "Ajouter une tâche...",
    "task.checklist": "Liste de contrôle",
    "task.no_subtasks": "Aucune sous-tâche.",
    "task.add_step": "Ajouter Étape",
    "task.add_item": "Ajouter élément",
    "task.add_new_step": "Ajouter nouvelle étape...",
    "task.edit_details": "Modifier Détails",
    "task.edit_title": "Modifier Tâche",
    "task.name": "Nom de la Tâche",
    "task.description": "Description",
    "task.subtasks": "Sous-tâches",
    "task.due_date": "Date d'échéance",
    "task.importance": "Importance",
    "task.priority": "Priorité",
    "task.important": "Important",
    "task.placeholder": "Tâche...",
    "timer.count": "Chrono",
    "timer.timer": "Minuteur",
    "timer.focusing": "Concentration...",
    "timer.recording": "Enregistrement",
    "timer.ready": "Prêt",
    "timer.stats": "Stats",
    "timer.daily_stats": "Aujourd'hui",
    "timer.total_sessions": "Sessions Totales",
    "timer.roll_dice": "Lancer les Dés",
    "timer.rolling": "Lancement...",
    "journal.quick_notes": "Notes Rapides",
    "journal.no_notes": "Pas encore de notes",
    "journal.title": "Journal",
    "journal.search": "Rechercher des notes...",
    "journal.not_found": "Aucune note trouvée.",
    "journal.unsaved": "Modifications non enregistrées...",
    "journal.saved": "Enregistré",
    "journal.title_placeholder": "Titre de la Note",
    "journal.content_placeholder": "Commencez à écrire...",
    "journal.select": "Sélectionnez une note",
    "journal.create_prompt": "ou créez une nouvelle entrée",
    "profile.title": "Profil et Compte",
    "profile.cloud_sync": "Sync Cloud",
    "profile.synced": "Actif et Synchronisé",
    "profile.local": "Inactif (Mode Local)",
    "profile.auth_error": "Erreur d'Authentification",
    "profile.sign_out": "Déconnexion",
    "profile.create_account": "Créer un Compte",
    "profile.sign_in": "Connexion pour Sync",
    "profile.google": "Google",
    "profile.or_email": "OU EMAIL",
    "profile.email_placeholder": "Adresse email",
    "profile.password_placeholder": "Mot de passe",
    "profile.sign_up": "S'inscrire",
    "profile.have_account": "Déjà un compte ? Connexion",
    "profile.no_account": "Pas de compte ? S'inscrire",
    "profile.exit_hub": "Quitter vers le Hub",
    "profile.upgrade": "Mettre à niveau",
    "profile.plan_free": "Plan Barista (Gratuit)",
    "profile.plan_pro": "Plan Connoisseur",
    "profile.plan_active": "Actif",
    "profile.plan_upgrade_hint": "Mettre à niveau pour Sync Cloud",
    "hub.welcome": "Bienvenue dans votre Suite",
    "hub.subtitle": "Sélectionnez une application.",
    "hub.app.focus": "Planificateur, minuteur et journal.",
    "hub.app.brainstorm": "Espace pour idées et cartes mentales.",
    "hub.app.vault": "Coffre-fort numérique sécurisé.",
    "hub.app.tools": "Dés, Roue, Pile ou Face, etc.",
    "hub.soon": "Bientôt",
    "settings.title": "Paramètres",
    "settings.theme": "Thème",
    "settings.language": "Langue",
    "settings.map_interface": "Carte et Interface",
    "settings.text_size": "Texte et Taille UI",
    "settings.snap": "Ancrage des Fenêtres",
    "settings.snap_desc": "Ancrer automatiquement les fenêtres.",
    "settings.autohide": "Masquer Contrôles",
    "settings.autohide_desc": "Masquer contrôles carte si inactif.",
    "map.zoom_in": "Zoom Avant",
    "map.zoom_out": "Zoom Arrière",
    "map.reset": "Réinitialiser",
    "map.arrange": "Arranger Fenêtres",
    "map.hide_controls": "Masquer Contrôles"
  },
  zh: {
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.save": "保存",
    "common.back": "返回",
    "common.today": "今天",
    "common.tomorrow": "明天",
    "common.add": "添加",
    "common.light_mode": "亮色模式",
    "common.dark_mode": "深色模式",
    "nav.list": "列表",
    "nav.calendar": "日历",
    "nav.map": "导图",
    "nav.focus": "专注",
    "nav.settings": "设置",
    "nav.profile": "个人资料",
    "nav.sync_local": "本地",
    "nav.sync_syncing": "同步中",
    "nav.sync_saved": "已保存",
    "nav.sync_error": "错误",
    "nav.sync_synced": "已同步",
    "dashboard.title": "任务列表",
    "dashboard.subtitle": "进行中与待办",
    "dashboard.active": "进行中",
    "dashboard.today_section": "今日专注",
    "dashboard.upcoming": "收件箱与待办",
    "dashboard.done": "已完成",
    "dashboard.no_active": "没有进行中的任务。",
    "dashboard.all_done": "大功告成！",
    "dashboard.all_done_desc": "您已完成今日的所有计划。",
    "smartadd.placeholder": "添加新任务...",
    "smartadd.description": "描述（可选）",
    "smartadd.add_task": "添加任务",
    "calendar.no_tasks": "今天没有任务。",
    "calendar.quick_add": "添加任务...",
    "task.checklist": "检查清单",
    "task.no_subtasks": "暂无子任务。",
    "task.add_step": "添加步骤",
    "task.add_item": "添加项目",
    "task.add_new_step": "添加新步骤...",
    "task.edit_details": "编辑详情",
    "task.edit_title": "编辑任务",
    "task.name": "任务名称",
    "task.description": "描述",
    "task.subtasks": "子任务",
    "task.due_date": "截止日期",
    "task.importance": "重要性",
    "task.priority": "优先级",
    "task.important": "重要",
    "task.placeholder": "任务...",
    "timer.count": "计时",
    "timer.timer": "倒计时",
    "timer.focusing": "专注中...",
    "timer.recording": "记录中",
    "timer.ready": "就绪",
    "timer.stats": "统计",
    "timer.daily_stats": "今天",
    "timer.total_sessions": "总专注次数",
    "timer.roll_dice": "掷骰子",
    "timer.rolling": "投掷中...",
    "journal.quick_notes": "快速笔记",
    "journal.no_notes": "暂无笔记",
    "journal.title": "日记",
    "journal.search": "搜索笔记...",
    "journal.not_found": "未找到笔记。",
    "journal.unsaved": "未保存...",
    "journal.saved": "已保存",
    "journal.title_placeholder": "笔记标题",
    "journal.content_placeholder": "开始写作...",
    "journal.select": "选择笔记查看",
    "journal.create_prompt": "或创建新条目",
    "profile.title": "个人资料与账户",
    "profile.cloud_sync": "云同步",
    "profile.synced": "已激活并同步",
    "profile.local": "未激活（本地模式）",
    "profile.auth_error": "认证错误",
    "profile.sign_out": "登出",
    "profile.create_account": "创建账户",
    "profile.sign_in": "登录以同步",
    "profile.google": "Google",
    "profile.or_email": "或 邮箱",
    "profile.email_placeholder": "邮箱地址",
    "profile.password_placeholder": "密码",
    "profile.sign_up": "注册",
    "profile.have_account": "已有账户？登录",
    "profile.no_account": "没有账户？注册",
    "profile.exit_hub": "退出至应用中心",
    "profile.upgrade": "升级",
    "profile.plan_free": "咖啡师计划（免费）",
    "profile.plan_pro": "鉴赏家计划",
    "profile.plan_active": "当前计划",
    "profile.plan_upgrade_hint": "升级以使用云同步",
    "hub.welcome": "欢迎使用",
    "hub.subtitle": "选择一个应用以启动。",
    "hub.app.focus": "每日计划、专注计时器与日记。",
    "hub.app.brainstorm": "创意构思与思维导图。",
    "hub.app.vault": "安全的数字资产保险箱。",
    "hub.app.tools": "骰子、转盘、抛硬币等。",
    "hub.soon": "即将推出",
    "settings.title": "设置",
    "settings.theme": "主题",
    "settings.language": "语言",
    "settings.map_interface": "地图与界面",
    "settings.text_size": "文字与界面大小",
    "settings.snap": "窗口吸附",
    "settings.snap_desc": "拖动时自动吸附窗口。",
    "settings.autohide": "自动隐藏控制",
    "settings.autohide_desc": "空闲时隐藏地图控制。",
    "map.zoom_in": "放大",
    "map.zoom_out": "缩小",
    "map.reset": "重置视图",
    "map.arrange": "排列窗口",
    "map.hide_controls": "隐藏控制"
  },
  ja: {
    "common.cancel": "キャンセル",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.save": "保存",
    "common.back": "戻る",
    "common.today": "今日",
    "common.tomorrow": "明日",
    "common.add": "追加",
    "common.light_mode": "ライトモード",
    "common.dark_mode": "ダークモード",
    "nav.list": "リスト",
    "nav.calendar": "カレンダー",
    "nav.map": "マップ",
    "nav.focus": "集中",
    "nav.settings": "設定",
    "nav.profile": "プロフィール",
    "nav.sync_local": "ローカル",
    "nav.sync_syncing": "同期中",
    "nav.sync_saved": "保存済",
    "nav.sync_error": "エラー",
    "nav.sync_synced": "同期済",
    "dashboard.title": "タスクリスト",
    "dashboard.subtitle": "アクティブ & 保留中",
    "dashboard.active": "アクティブ",
    "dashboard.today_section": "今日のフォーカス",
    "dashboard.upcoming": "受信箱 & 今後",
    "dashboard.done": "完了",
    "dashboard.no_active": "アクティブなタスクはありません。",
    "dashboard.all_done": "完了しました！",
    "dashboard.all_done_desc": "今日の予定はすべて完了しました。",
    "smartadd.placeholder": "新しいタスクを追加...",
    "smartadd.description": "説明（オプション）",
    "smartadd.add_task": "タスク追加",
    "calendar.no_tasks": "この日のタスクはありません。",
    "calendar.quick_add": "タスクを追加...",
    "task.checklist": "チェックリスト",
    "task.no_subtasks": "サブタスクなし。",
    "task.add_step": "ステップ追加",
    "task.add_item": "項目追加",
    "task.add_new_step": "新しいステップ...",
    "task.edit_details": "詳細を編集",
    "task.edit_title": "タスク編集",
    "task.name": "タスク名",
    "task.description": "説明",
    "task.subtasks": "サブタスク",
    "task.due_date": "期日",
    "task.importance": "重要度",
    "task.priority": "優先度",
    "task.important": "重要",
    "task.placeholder": "タスク...",
    "timer.count": "カウント",
    "timer.timer": "タイマー",
    "timer.focusing": "集中中...",
    "timer.recording": "記録中",
    "timer.ready": "準備完了",
    "timer.stats": "統計",
    "timer.daily_stats": "今日",
    "timer.total_sessions": "総セッション",
    "timer.roll_dice": "サイコロを振る",
    "timer.rolling": "回転中...",
    "journal.quick_notes": "クイックメモ",
    "journal.no_notes": "メモはまだありません",
    "journal.title": "ジャーナル",
    "journal.search": "メモを検索...",
    "journal.not_found": "メモが見つかりません。",
    "journal.unsaved": "未保存の変更...",
    "journal.saved": "保存済",
    "journal.title_placeholder": "タイトル",
    "journal.content_placeholder": "書き始める...",
    "journal.select": "メモを選択",
    "journal.create_prompt": "または新規作成",
    "profile.title": "プロフィールとアカウント",
    "profile.cloud_sync": "クラウド同期",
    "profile.synced": "有効 & 同期済",
    "profile.local": "無効（ローカルモード）",
    "profile.auth_error": "認証エラー",
    "profile.sign_out": "ログアウト",
    "profile.create_account": "アカウント作成",
    "profile.sign_in": "ログインして同期",
    "profile.google": "Google",
    "profile.or_email": "または メール",
    "profile.email_placeholder": "メールアドレス",
    "profile.password_placeholder": "パスワード",
    "profile.sign_up": "登録",
    "profile.have_account": "アカウントをお持ちですか？ログイン",
    "profile.no_account": "アカウントがありませんか？登録",
    "profile.exit_hub": "ハブへ戻る",
    "profile.upgrade": "アップグレード",
    "profile.plan_free": "バリスタプラン（無料）",
    "profile.plan_pro": "コノシュアプラン",
    "profile.plan_active": "有効",
    "profile.plan_upgrade_hint": "クラウド同期のためにアップグレード",
    "hub.welcome": "ようこそ",
    "hub.subtitle": "アプリを選択して起動してください。",
    "hub.app.focus": "デイリープランナー、タイマー、ジャーナル。",
    "hub.app.brainstorm": "アイデアとマインドマップ。",
    "hub.app.vault": "安全なデジタル保管庫。",
    "hub.app.tools": "サイコロ、ルーレット、コイントスなど。",
    "hub.soon": "近日公開",
    "settings.title": "設定",
    "settings.theme": "テーマ",
    "settings.language": "言語",
    "settings.map_interface": "マップとインターフェース",
    "settings.text_size": "文字とUIサイズ",
    "settings.snap": "ウィンドウスナップ",
    "settings.snap_desc": "ドラッグ時にウィンドウを自動配置。",
    "settings.autohide": "操作を自動的に隠す",
    "settings.autohide_desc": "アイドル時にマップ操作を隠す。",
    "map.zoom_in": "拡大",
    "map.zoom_out": "縮小",
    "map.reset": "リセット",
    "map.arrange": "整列",
    "map.hide_controls": "操作を隠す"
  },
  ko: {
    "common.cancel": "취소",
    "common.delete": "삭제",
    "common.edit": "편집",
    "common.save": "저장",
    "common.back": "뒤로",
    "common.today": "오늘",
    "common.tomorrow": "내일",
    "common.add": "추가",
    "common.light_mode": "라이트 모드",
    "common.dark_mode": "다크 모드",
    "nav.list": "목록",
    "nav.calendar": "달력",
    "nav.map": "지도",
    "nav.focus": "집중",
    "nav.settings": "설정",
    "nav.profile": "프로필",
    "nav.sync_local": "로컬",
    "nav.sync_syncing": "동기화 중",
    "nav.sync_saved": "저장됨",
    "nav.sync_error": "오류",
    "nav.sync_synced": "동기화됨",
    "dashboard.title": "작업 목록",
    "dashboard.subtitle": "진행 중 & 대기 중",
    "dashboard.active": "진행 중",
    "dashboard.today_section": "오늘의 집중",
    "dashboard.upcoming": "보관함 및 예정",
    "dashboard.done": "완료됨",
    "dashboard.no_active": "진행 중인 작업이 없습니다.",
    "dashboard.all_done": "모두 완료!",
    "dashboard.all_done_desc": "오늘 예정된 모든 작업을 완료했습니다.",
    "smartadd.placeholder": "새 작업 추가...",
    "smartadd.description": "설명 (선택 사항)",
    "smartadd.add_task": "작업 추가",
    "calendar.no_tasks": "이 날의 작업이 없습니다.",
    "calendar.quick_add": "작업 추가...",
    "task.checklist": "체크리스트",
    "task.no_subtasks": "하위 작업 없음.",
    "task.add_step": "단계 추가",
    "task.add_item": "항목 추가",
    "task.add_new_step": "새 단계 추가...",
    "task.edit_details": "상세 편집",
    "task.edit_title": "작업 편집",
    "task.name": "작업 이름",
    "task.description": "설명",
    "task.subtasks": "하위 작업",
    "task.due_date": "마감일",
    "task.importance": "중요도",
    "task.priority": "우선순위",
    "task.important": "중요",
    "task.placeholder": "작업...",
    "timer.count": "카운트",
    "timer.timer": "타이머",
    "timer.focusing": "집중 중...",
    "timer.recording": "기록 중",
    "timer.ready": "준비",
    "timer.stats": "통계",
    "timer.daily_stats": "오늘",
    "timer.total_sessions": "총 세션",
    "timer.roll_dice": "주사위 굴리기",
    "timer.rolling": "굴리는 중...",
    "journal.quick_notes": "빠른 메모",
    "journal.no_notes": "메모 없음",
    "journal.title": "일기",
    "journal.search": "메모 검색...",
    "journal.not_found": "메모를 찾을 수 없습니다.",
    "journal.unsaved": "저장되지 않은 변경사항...",
    "journal.saved": "저장됨",
    "journal.title_placeholder": "메모 제목",
    "journal.content_placeholder": "작성 시작...",
    "journal.select": "메모 선택",
    "journal.create_prompt": "또는 새 항목 작성",
    "profile.title": "프로필 및 계정",
    "profile.cloud_sync": "클라우드 동기화",
    "profile.synced": "활성 & 동기화됨",
    "profile.local": "비활성 (로컬 모드)",
    "profile.auth_error": "인증 오류",
    "profile.sign_out": "로그아웃",
    "profile.create_account": "계정 생성",
    "profile.sign_in": "로그인하여 동기화",
    "profile.google": "Google",
    "profile.or_email": "또는 이메일",
    "profile.email_placeholder": "이메일 주소",
    "profile.password_placeholder": "비밀번호",
    "profile.sign_up": "가입",
    "profile.have_account": "계정이 있으신가요? 로그인",
    "profile.no_account": "계정이 없으신가요? 가입",
    "profile.exit_hub": "앱 허브로 나가기",
    "profile.upgrade": "업그레이드",
    "profile.plan_free": "바리스타 플랜 (무료)",
    "profile.plan_pro": "코노셔 플랜",
    "profile.plan_active": "활성",
    "profile.plan_upgrade_hint": "클라우드 동기화를 위해 업그레이드",
    "hub.welcome": "환영합니다",
    "hub.subtitle": "실행할 애플리케이션을 선택하세요.",
    "hub.app.focus": "일일 플래너, 타이머 및 일기.",
    "hub.app.brainstorm": "아이디어와 마인드맵을 위한 캔버스.",
    "hub.app.vault": "안전한 디지털 보관함.",
    "hub.app.tools": "주사위, 룰렛, 동전 던지기 등.",
    "hub.soon": "곧 출시",
    "settings.title": "설정",
    "settings.theme": "테마",
    "settings.language": "언어",
    "settings.map_interface": "지도 및 인터페이스",
    "settings.text_size": "텍스트 및 UI 크기",
    "settings.snap": "창 스냅",
    "settings.snap_desc": "드래그 시 창을 가장자리에 자동 맞춤.",
    "settings.autohide": "컨트롤 자동 숨김",
    "settings.autohide_desc": "유휴 상태일 때 지도 컨트롤 숨김.",
    "map.zoom_in": "확대",
    "map.zoom_out": "축소",
    "map.reset": "뷰 초기화",
    "map.arrange": "창 정렬",
    "map.hide_controls": "컨트롤 숨기기"
  }
};

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const ThemeProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [theme, setTheme] = useState<Theme>(() => {
    const saved = localStorage.getItem('loffeeflow_theme');
    return (saved as Theme) || 'light';
  });

  const [uiSize, setUiSizeState] = useState<UISize>(() => {
    const saved = localStorage.getItem('loffeeflow_size');
    return (saved as UISize) || 'medium';
  });

  const [snapEnabled, setSnapEnabled] = useState<boolean>(() => {
    const saved = localStorage.getItem('loffeeflow_snap');
    return saved === null ? true : saved === 'true';
  });

  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('loffeeflow_lang');
    return (saved as Language) || 'en';
  });

  const [autoHideControls, setAutoHideControls] = useState<boolean>(() => {
    const saved = localStorage.getItem('loffeeflow_autohide');
    return saved === null ? true : saved === 'true';
  });

  const [autoHideDuration, setAutoHideDurationState] = useState<number>(() => {
    const saved = localStorage.getItem('loffeeflow_autohide_duration');
    return saved ? parseInt(saved, 10) : 5000;
  });

  // Apply Theme
  useEffect(() => {
    localStorage.setItem('loffeeflow_theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  // Apply UI Size (Scaling root font-size)
  useEffect(() => {
    localStorage.setItem('loffeeflow_size', uiSize);
    const root = document.documentElement;
    switch (uiSize) {
        case 'small':
            root.style.fontSize = '90%'; // Approx 14.4px base
            break;
        case 'medium':
            root.style.fontSize = '100%'; // 16px base
            break;
        case 'large':
            root.style.fontSize = '112.5%'; // 18px base
            break;
    }
  }, [uiSize]);

  // Persist Snap Setting
  useEffect(() => {
    localStorage.setItem('loffeeflow_snap', String(snapEnabled));
  }, [snapEnabled]);

  // Persist AutoHide Settings
  useEffect(() => {
    localStorage.setItem('loffeeflow_autohide', String(autoHideControls));
  }, [autoHideControls]);

  useEffect(() => {
    localStorage.setItem('loffeeflow_autohide_duration', String(autoHideDuration));
  }, [autoHideDuration]);

  // Apply Language
  useEffect(() => {
    localStorage.setItem('loffeeflow_lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'light' ? 'dark' : 'light');
  };

  const setUiSize = (size: UISize) => {
      setUiSizeState(size);
  };

  const toggleSnap = () => {
      setSnapEnabled(prev => !prev);
  };

  const setLanguage = (lang: Language) => {
      setLanguageState(lang);
  };

  const toggleAutoHide = () => {
      setAutoHideControls(prev => !prev);
  };

  const setAutoHideDuration = (ms: number) => {
      setAutoHideDurationState(ms);
  };

  const t = (key: string): string => {
      return translations[language][key] || key;
  };

  return (
    <ThemeContext.Provider value={{ 
        theme, uiSize, snapEnabled, language, autoHideControls, autoHideDuration,
        toggleTheme, setUiSize, toggleSnap, setLanguage, toggleAutoHide, setAutoHideDuration, t
    }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};
