
import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Theme = 'light' | 'dark';
type UISize = 'small' | 'medium' | 'large';
export type Language = 'en' | 'es' | 'fr' | 'zh' | 'ja' | 'ko';

interface ThemeContextType {
  theme: Theme;
  uiSize: UISize;
  snapEnabled: boolean;
  language: Language;
  autoHideControls: boolean;
  autoHideDuration: number;
  autoDeleteOverdue: boolean;
  toggleTheme: () => void;
  setUiSize: (size: UISize) => void;
  toggleSnap: () => void;
  setLanguage: (lang: Language) => void;
  toggleAutoHide: () => void;
  toggleAutoDeleteOverdue: () => void;
  setAutoHideDuration: (ms: number) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.back": "Back",
    "common.today": "Today",
    "common.tomorrow": "Tomorrow",
    "common.light_mode": "Light Mode",
    "common.dark_mode": "Dark Mode",
    "nav.list": "List",
    "nav.calendar": "Calendar",
    "nav.map": "Timeline",
    "nav.focus": "Focus",
    "nav.settings": "Settings",
    "nav.sync_local": "Local",
    "nav.sync_syncing": "Syncing",
    "nav.sync_saved": "Saved",
    "nav.sync_synced": "Synced",
    "nav.sync_error": "Error",
    "dashboard.title": "Daily Planner",
    "dashboard.subtitle": "Find your flow",
    "dashboard.today_section": "Today's Focus",
    "dashboard.upcoming": "Next Steps",
    "dashboard.done": "Completed",
    "dashboard.all_done": "All Caught Up!",
    "dashboard.all_done_desc": "You've completed everything for today. Enjoy your free time!",
    "dashboard.no_active": "No active tasks",
    "smartadd.placeholder": "What's on your mind?",
    "smartadd.description": "Add details...",
    "smartadd.add_task": "Plan Task",
    "timer.count": "Count",
    "timer.timer": "Timer",
    "timer.focusing": "Focusing...",
    "timer.recording": "Recording...",
    "timer.ready": "Ready",
    "timer.stats": "Daily Focus",
    "timer.daily_stats": "Today's Focus",
    "timer.total_sessions": "Total Sessions",
    "settings.title": "Preferences",
    "settings.theme": "Appearance",
    "settings.language": "Language",
    "settings.text_size": "Text Size",
    "settings.auto_delete": "Auto-delete old tasks",
    "settings.auto_delete_hint": "Delete tasks overdue > 3 days",
    "task.important": "Important",
    "task.priority": "Priority",
    "task.edit_title": "Edit Task",
    "task.placeholder": "Task details...",
    "task.name": "Task Name",
    "task.description": "Description",
    "task.checklist": "Checklist",
    "task.subtasks": "Subtasks",
    "task.add_item": "Add Item",
    "task.add_new_step": "Add new step...",
    "task.add_step": "Add step",
    "task.due_date": "Due Date",
    "task.importance": "Importance",
    "task.edit_details": "Edit Details",
    "task.no_subtasks": "No subtasks yet",
    "calendar.no_tasks": "No tasks for this day",
    "calendar.quick_add": "Quick add task...",
    "profile.title": "Account",
    "profile.cloud_sync": "Cloud Sync",
    "profile.synced": "Synced",
    "profile.local": "Local Only",
    "profile.auth_error": "Authentication Error",
    "profile.plan_pro": "Pro Plan",
    "profile.plan_free": "Free Plan",
    "profile.plan_active": "Active",
    "profile.plan_upgrade_hint": "Upgrade for sync",
    "profile.upgrade": "Upgrade",
    "profile.sign_out": "Sign Out",
    "profile.create_account": "Create Account",
    "profile.sign_in": "Sign In",
    "profile.google": "Continue with Google",
    "profile.or_email": "Or with email",
    "profile.email_placeholder": "Email address",
    "profile.password_placeholder": "Password",
    "profile.sign_up": "Sign Up",
    "profile.have_account": "Already have an account?",
    "profile.no_account": "Don't have an account?",
    "profile.exit_hub": "Back to Hub",
    "journal.title": "Journal",
    "journal.quick_notes": "Quick Notes",
    "journal.no_notes": "No notes yet",
    "journal.search": "Search notes...",
    "journal.not_found": "No notes found",
    "journal.unsaved": "Unsaved",
    "journal.saved": "Saved",
    "journal.title_placeholder": "Title",
    "journal.content_placeholder": "Start writing...",
    "journal.select": "Select a note",
    "journal.create_prompt": "Select a note from the list or create a new one.",
    "hub.welcome": "Welcome back",
    "hub.subtitle": "What would you like to do?",
    "hub.app.focus": "Daily planner & timer",
    "hub.app.brainstorm": "Free-form ideation",
    "hub.app.vault": "Secure storage",
    "hub.app.tools": "Utilities",
    "hub.soon": "Soon",
    "map.zoom_in": "Zoom In",
    "map.zoom_out": "Zoom Out",
    "map.reset": "Reset View"
  },
  es: {
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.save": "Guardar",
    "common.back": "Atrás",
    "common.today": "Hoy",
    "common.tomorrow": "Mañana",
    "common.light_mode": "Modo Claro",
    "common.dark_mode": "Modo Oscuro",
    "nav.list": "Lista",
    "nav.calendar": "Calendario",
    "nav.map": "Línea de Tiempo",
    "nav.focus": "Enfoque",
    "nav.settings": "Ajustes",
    "nav.sync_local": "Local",
    "nav.sync_syncing": "Sincronizando",
    "nav.sync_saved": "Guardado",
    "nav.sync_synced": "Sincronizado",
    "nav.sync_error": "Error",
    "dashboard.title": "Planificador",
    "dashboard.subtitle": "Encuentra tu flujo",
    "dashboard.today_section": "Enfoque de Hoy",
    "dashboard.upcoming": "Próximos Pasos",
    "dashboard.done": "Completado",
    "dashboard.all_done": "¡Todo al Día!",
    "dashboard.all_done_desc": "Has completado todo por hoy. ¡Disfruta tu tiempo libre!",
    "dashboard.no_active": "Sin tareas activas",
    "smartadd.placeholder": "¿Qué tienes en mente?",
    "smartadd.description": "Añadir detalles...",
    "smartadd.add_task": "Planificar Tarea",
    "timer.count": "Cronómetro",
    "timer.timer": "Temporizador",
    "timer.focusing": "Enfocando...",
    "timer.recording": "Grabando...",
    "timer.ready": "Listo",
    "timer.stats": "Enfoque Diario",
    "timer.daily_stats": "Enfoque de Hoy",
    "timer.total_sessions": "Total Sesiones",
    "settings.title": "Preferencias",
    "settings.theme": "Apariencia",
    "settings.language": "Idioma",
    "settings.text_size": "Tamaño de Texto",
    "settings.auto_delete": "Auto-eliminar tareas",
    "settings.auto_delete_hint": "Eliminar vencidas > 3 días",
    "task.important": "Importante",
    "task.priority": "Prioridad",
    "task.edit_title": "Editar Tarea",
    "task.placeholder": "Detalles de la tarea...",
    "task.name": "Nombre de Tarea",
    "task.description": "Descripción",
    "task.checklist": "Lista de control",
    "task.subtasks": "Subtareas",
    "task.add_item": "Añadir ítem",
    "task.add_new_step": "Añadir nuevo paso...",
    "task.add_step": "Añadir paso",
    "task.due_date": "Fecha de Vencimiento",
    "task.importance": "Importancia",
    "task.edit_details": "Editar Detalles",
    "task.no_subtasks": "Sin subtareas aún",
    "calendar.no_tasks": "Sin tareas para este día",
    "calendar.quick_add": "Añadir tarea rápida...",
    "profile.title": "Cuenta",
    "profile.cloud_sync": "Sincronización Nube",
    "profile.synced": "Sincronizado",
    "profile.local": "Solo Local",
    "profile.auth_error": "Error de Autenticación",
    "profile.plan_pro": "Plan Pro",
    "profile.plan_free": "Plan Gratuito",
    "profile.plan_active": "Activo",
    "profile.plan_upgrade_hint": "Mejora para sincronizar",
    "profile.upgrade": "Mejorar",
    "profile.sign_out": "Cerrar Sesión",
    "profile.create_account": "Crear Cuenta",
    "profile.sign_in": "Iniciar Sesión",
    "profile.google": "Continuar con Google",
    "profile.or_email": "O con correo",
    "profile.email_placeholder": "Dirección de correo",
    "profile.password_placeholder": "Contraseña",
    "profile.sign_up": "Registrarse",
    "profile.have_account": "¿Ya tienes cuenta?",
    "profile.no_account": "¿No tienes cuenta?",
    "profile.exit_hub": "Volver al Hub",
    "journal.title": "Diario",
    "journal.quick_notes": "Notas Rápidas",
    "journal.no_notes": "Sin notas aún",
    "journal.search": "Buscar notas...",
    "journal.not_found": "No se encontraron notas",
    "journal.unsaved": "Sin guardar",
    "journal.saved": "Guardado",
    "journal.title_placeholder": "Título",
    "journal.content_placeholder": "Empieza a escribir...",
    "journal.select": "Selecciona una nota",
    "journal.create_prompt": "Selecciona una nota de la lista o crea una nueva.",
    "hub.welcome": "Bienvenido de nuevo",
    "hub.subtitle": "¿Qué te gustaría hacer?",
    "hub.app.focus": "Planificador diario y temporizador",
    "hub.app.brainstorm": "Ideación libre",
    "hub.app.vault": "Almacenamiento seguro",
    "hub.app.tools": "Utilidades",
    "hub.soon": "Pronto",
    "map.zoom_in": "Acercar",
    "map.zoom_out": "Alejar",
    "map.reset": "Restablecer"
  },
  fr: {
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.save": "Enregistrer",
    "common.back": "Retour",
    "common.today": "Aujourd'hui",
    "common.tomorrow": "Demain",
    "common.light_mode": "Mode Clair",
    "common.dark_mode": "Mode Sombre",
    "nav.list": "Liste",
    "nav.calendar": "Calendrier",
    "nav.map": "Chronologie",
    "nav.focus": "Focus",
    "nav.settings": "Paramètres",
    "nav.sync_local": "Local",
    "nav.sync_syncing": "Sync...",
    "nav.sync_saved": "Enregistré",
    "nav.sync_synced": "Synchronisé",
    "nav.sync_error": "Erreur",
    "dashboard.title": "Planificateur",
    "dashboard.subtitle": "Trouvez votre rythme",
    "dashboard.today_section": "Focus du Jour",
    "dashboard.upcoming": "Prochaines Étapes",
    "dashboard.done": "Terminé",
    "dashboard.all_done": "Tout est à jour !",
    "dashboard.all_done_desc": "Vous avez tout terminé pour aujourd'hui. Profitez de votre temps libre !",
    "dashboard.no_active": "Aucune tâche active",
    "smartadd.placeholder": "Qu'avez-vous en tête ?",
    "smartadd.description": "Ajouter des détails...",
    "smartadd.add_task": "Planifier",
    "timer.count": "Chrono",
    "timer.timer": "Minuteur",
    "timer.focusing": "Concentration...",
    "timer.recording": "Enregistrement...",
    "timer.ready": "Prêt",
    "timer.stats": "Focus Quotidien",
    "timer.daily_stats": "Focus du Jour",
    "timer.total_sessions": "Total Sessions",
    "settings.title": "Préférences",
    "settings.theme": "Apparence",
    "settings.language": "Langue",
    "settings.text_size": "Taille du Texte",
    "settings.auto_delete": "Suppression auto",
    "settings.auto_delete_hint": "Supprimer tâches > 3 jours",
    "task.important": "Important",
    "task.priority": "Priorité",
    "task.edit_title": "Modifier la tâche",
    "task.placeholder": "Détails de la tâche...",
    "task.name": "Nom de la tâche",
    "task.description": "Description",
    "task.checklist": "Liste de contrôle",
    "task.subtasks": "Sous-tâches",
    "task.add_item": "Ajouter un élément",
    "task.add_new_step": "Ajouter une étape...",
    "task.add_step": "Ajouter étape",
    "task.due_date": "Date d'échéance",
    "task.importance": "Importance",
    "task.edit_details": "Modifier détails",
    "task.no_subtasks": "Pas encore de sous-tâches",
    "calendar.no_tasks": "Pas de tâches pour ce jour",
    "calendar.quick_add": "Ajout rapide...",
    "profile.title": "Compte",
    "profile.cloud_sync": "Sync Cloud",
    "profile.synced": "Synchronisé",
    "profile.local": "Local Seulement",
    "profile.auth_error": "Erreur d'authentification",
    "profile.plan_pro": "Plan Pro",
    "profile.plan_free": "Plan Gratuit",
    "profile.plan_active": "Actif",
    "profile.plan_upgrade_hint": "Mettre à niveau pour sync",
    "profile.upgrade": "Mettre à niveau",
    "profile.sign_out": "Déconnexion",
    "profile.create_account": "Créer un compte",
    "profile.sign_in": "Connexion",
    "profile.google": "Continuer avec Google",
    "profile.or_email": "Ou avec email",
    "profile.email_placeholder": "Adresse email",
    "profile.password_placeholder": "Mot de passe",
    "profile.sign_up": "S'inscrire",
    "profile.have_account": "Déjà un compte ?",
    "profile.no_account": "Pas de compte ?",
    "profile.exit_hub": "Retour au Hub",
    "journal.title": "Journal",
    "journal.quick_notes": "Notes Rapides",
    "journal.no_notes": "Pas encore de notes",
    "journal.search": "Rechercher...",
    "journal.not_found": "Aucune note trouvée",
    "journal.unsaved": "Non enregistré",
    "journal.saved": "Enregistré",
    "journal.title_placeholder": "Titre",
    "journal.content_placeholder": "Commencez à écrire...",
    "journal.select": "Sélectionnez une note",
    "journal.create_prompt": "Sélectionnez une note ou créez-en une nouvelle.",
    "hub.welcome": "Bon retour",
    "hub.subtitle": "Que souhaitez-vous faire ?",
    "hub.app.focus": "Planificateur quotidien",
    "hub.app.brainstorm": "Idéation libre",
    "hub.app.vault": "Stockage sécurisé",
    "hub.app.tools": "Utilitaires",
    "hub.soon": "Bientôt",
    "map.zoom_in": "Zoom Avant",
    "map.zoom_out": "Zoom Arrière",
    "map.reset": "Réinitialiser"
  },
  zh: {
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.save": "保存",
    "common.back": "返回",
    "common.today": "今天",
    "common.tomorrow": "明天",
    "common.light_mode": "日间模式",
    "common.dark_mode": "夜间模式",
    "nav.list": "列表",
    "nav.calendar": "日历",
    "nav.map": "时间轴",
    "nav.focus": "专注",
    "nav.settings": "设置",
    "nav.sync_local": "本地",
    "nav.sync_syncing": "同步中",
    "nav.sync_saved": "已保存",
    "nav.sync_synced": "已同步",
    "nav.sync_error": "错误",
    "dashboard.title": "日常计划",
    "dashboard.subtitle": "找到你的节奏",
    "dashboard.today_section": "今日专注",
    "dashboard.upcoming": "下一步",
    "dashboard.done": "已完成",
    "dashboard.all_done": "全部搞定！",
    "dashboard.all_done_desc": "你已完成今天的所有任务。享受你的自由时间吧！",
    "dashboard.no_active": "没有活动任务",
    "smartadd.placeholder": "在想什么？",
    "smartadd.description": "添加详情...",
    "smartadd.add_task": "计划任务",
    "timer.count": "计时",
    "timer.timer": "倒计时",
    "timer.focusing": "专注中...",
    "timer.recording": "记录中...",
    "timer.ready": "准备",
    "timer.stats": "每日专注",
    "timer.daily_stats": "今日专注",
    "timer.total_sessions": "总次数",
    "settings.title": "偏好设置",
    "settings.theme": "外观",
    "settings.language": "语言",
    "settings.text_size": "文字大小",
    "settings.auto_delete": "自动删除旧任务",
    "settings.auto_delete_hint": "删除过期超过 3 天的任务",
    "task.important": "重要",
    "task.priority": "优先级",
    "task.edit_title": "编辑任务",
    "task.placeholder": "任务详情...",
    "task.name": "任务名称",
    "task.description": "描述",
    "task.checklist": "检查清单",
    "task.subtasks": "子任务",
    "task.add_item": "添加项目",
    "task.add_new_step": "添加新步骤...",
    "task.add_step": "添加步骤",
    "task.due_date": "截止日期",
    "task.importance": "重要性",
    "task.edit_details": "编辑详情",
    "task.no_subtasks": "暂无子任务",
    "calendar.no_tasks": "今天没有任务",
    "calendar.quick_add": "快速添加任务...",
    "profile.title": "账户",
    "profile.cloud_sync": "云同步",
    "profile.synced": "已同步",
    "profile.local": "仅本地",
    "profile.auth_error": "认证错误",
    "profile.plan_pro": "专业版",
    "profile.plan_free": "免费版",
    "profile.plan_active": "活跃",
    "profile.plan_upgrade_hint": "升级以同步",
    "profile.upgrade": "升级",
    "profile.sign_out": "退出登录",
    "profile.create_account": "创建账户",
    "profile.sign_in": "登录",
    "profile.google": "通过 Google 继续",
    "profile.or_email": "或使用邮箱",
    "profile.email_placeholder": "邮箱地址",
    "profile.password_placeholder": "密码",
    "profile.sign_up": "注册",
    "profile.have_account": "已有账户？",
    "profile.no_account": "没有账户？",
    "profile.exit_hub": "返回中心",
    "journal.title": "日志",
    "journal.quick_notes": "快速笔记",
    "journal.no_notes": "暂无笔记",
    "journal.search": "搜索笔记...",
    "journal.not_found": "未找到笔记",
    "journal.unsaved": "未保存",
    "journal.saved": "已保存",
    "journal.title_placeholder": "标题",
    "journal.content_placeholder": "开始写作...",
    "journal.select": "选择一个笔记",
    "journal.create_prompt": "从列表中选择笔记或创建一个新笔记。",
    "hub.welcome": "欢迎回来",
    "hub.subtitle": "你想做什么？",
    "hub.app.focus": "日常计划与计时",
    "hub.app.brainstorm": "自由构思",
    "hub.app.vault": "安全存储",
    "hub.app.tools": "工具箱",
    "hub.soon": "敬请期待",
    "map.zoom_in": "放大",
    "map.zoom_out": "缩小",
    "map.reset": "重置"
  },
  ja: {
    "common.cancel": "キャンセル",
    "common.delete": "削除",
    "common.save": "保存",
    "common.back": "戻る",
    "common.today": "今日",
    "common.tomorrow": "明日",
    "common.light_mode": "ライトモード",
    "common.dark_mode": "ダークモード",
    "nav.list": "リスト",
    "nav.calendar": "カレンダー",
    "nav.map": "タイムライン",
    "nav.focus": "集中",
    "nav.settings": "設定",
    "nav.sync_local": "ローカル",
    "nav.sync_syncing": "同期中",
    "nav.sync_saved": "保存済",
    "nav.sync_synced": "同期済",
    "nav.sync_error": "エラー",
    "dashboard.title": "デイリープランナー",
    "dashboard.subtitle": "フローを見つける",
    "dashboard.today_section": "今日のフォーカス",
    "dashboard.upcoming": "次のステップ",
    "dashboard.done": "完了",
    "dashboard.all_done": "すべて完了！",
    "dashboard.all_done_desc": "今日のタスクはすべて完了しました。自由な時間を楽しんでください！",
    "dashboard.no_active": "アクティブなタスクはありません",
    "smartadd.placeholder": "何を考えていますか？",
    "smartadd.description": "詳細を追加...",
    "smartadd.add_task": "タスクを計画",
    "timer.count": "カウント",
    "timer.timer": "タイマー",
    "timer.focusing": "集中中...",
    "timer.recording": "記録中...",
    "timer.ready": "準備完了",
    "timer.stats": "毎日の集中",
    "timer.daily_stats": "今日の集中",
    "timer.total_sessions": "総セッション",
    "settings.title": "設定",
    "settings.theme": "外観",
    "settings.language": "言語",
    "settings.text_size": "文字サイズ",
    "settings.auto_delete": "タスクの自動削除",
    "settings.auto_delete_hint": "3日以上経過したタスクを削除",
    "task.important": "重要",
    "task.priority": "優先度",
    "task.edit_title": "タスクを編集",
    "task.placeholder": "タスクの詳細...",
    "task.name": "タスク名",
    "task.description": "説明",
    "task.checklist": "チェックリスト",
    "task.subtasks": "サブタスク",
    "task.add_item": "項目を追加",
    "task.add_new_step": "新しいステップを追加...",
    "task.add_step": "ステップを追加",
    "task.due_date": "期限",
    "task.importance": "重要度",
    "task.edit_details": "詳細を編集",
    "task.no_subtasks": "サブタスクはまだありません",
    "calendar.no_tasks": "この日のタスクはありません",
    "calendar.quick_add": "クイック追加...",
    "profile.title": "アカウント",
    "profile.cloud_sync": "クラウド同期",
    "profile.synced": "同期済み",
    "profile.local": "ローカルのみ",
    "profile.auth_error": "認証エラー",
    "profile.plan_pro": "Proプラン",
    "profile.plan_free": "無料プラン",
    "profile.plan_active": "有効",
    "profile.plan_upgrade_hint": "同期のためにアップグレード",
    "profile.upgrade": "アップグレード",
    "profile.sign_out": "ログアウト",
    "profile.create_account": "アカウント作成",
    "profile.sign_in": "ログイン",
    "profile.google": "Googleで続行",
    "profile.or_email": "またはメールで",
    "profile.email_placeholder": "メールアドレス",
    "profile.password_placeholder": "パスワード",
    "profile.sign_up": "登録",
    "profile.have_account": "アカウントをお持ちですか？",
    "profile.no_account": "アカウントがありませんか？",
    "profile.exit_hub": "ハブに戻る",
    "journal.title": "ジャーナル",
    "journal.quick_notes": "クイックノート",
    "journal.no_notes": "ノートはまだありません",
    "journal.search": "ノートを検索...",
    "journal.not_found": "ノートが見つかりません",
    "journal.unsaved": "未保存",
    "journal.saved": "保存済み",
    "journal.title_placeholder": "タイトル",
    "journal.content_placeholder": "書き始める...",
    "journal.select": "ノートを選択",
    "journal.create_prompt": "リストからノートを選択するか、新しいノートを作成してください。",
    "hub.welcome": "お帰りなさい",
    "hub.subtitle": "何をしますか？",
    "hub.app.focus": "デイリープランナー＆タイマー",
    "hub.app.brainstorm": "自由な発想",
    "hub.app.vault": "安全なストレージ",
    "hub.app.tools": "ユーティリティ",
    "hub.soon": "近日公開",
    "map.zoom_in": "拡大",
    "map.zoom_out": "縮小",
    "map.reset": "リセット"
  },
  ko: {
    "common.cancel": "취소",
    "common.delete": "삭제",
    "common.save": "저장",
    "common.back": "뒤로",
    "common.today": "오늘",
    "common.tomorrow": "내일",
    "common.light_mode": "라이트 모드",
    "common.dark_mode": "다크 모드",
    "nav.list": "목록",
    "nav.calendar": "달력",
    "nav.map": "타임라인",
    "nav.focus": "집중",
    "nav.settings": "설정",
    "nav.sync_local": "로컬",
    "nav.sync_syncing": "동기화 중",
    "nav.sync_saved": "저장됨",
    "nav.sync_synced": "동기화됨",
    "nav.sync_error": "오류",
    "dashboard.title": "데일리 플래너",
    "dashboard.subtitle": "나만의 흐름 찾기",
    "dashboard.today_section": "오늘의 집중",
    "dashboard.upcoming": "다음 할 일",
    "dashboard.done": "완료됨",
    "dashboard.all_done": "모두 완료!",
    "dashboard.all_done_desc": "오늘의 모든 할 일을 마쳤습니다. 자유 시간을 즐기세요!",
    "dashboard.no_active": "진행 중인 작업 없음",
    "smartadd.placeholder": "무슨 생각을 하고 계신가요?",
    "smartadd.description": "세부 정보 추가...",
    "smartadd.add_task": "작업 계획",
    "timer.count": "카운트",
    "timer.timer": "타이머",
    "timer.focusing": "집중 중...",
    "timer.recording": "기록 중...",
    "timer.ready": "준비",
    "timer.stats": "일일 집중",
    "timer.daily_stats": "오늘의 집중",
    "timer.total_sessions": "총 세션",
    "settings.title": "환경 설정",
    "settings.theme": "테마",
    "settings.language": "언어",
    "settings.text_size": "글자 크기",
    "settings.auto_delete": "자동 삭제",
    "settings.auto_delete_hint": "3일 이상 지난 작업 삭제",
    "task.important": "중요",
    "task.priority": "우선순위",
    "task.edit_title": "작업 편집",
    "task.placeholder": "작업 세부 정보...",
    "task.name": "작업 이름",
    "task.description": "설명",
    "task.checklist": "체크리스트",
    "task.subtasks": "하위 작업",
    "task.add_item": "항목 추가",
    "task.add_new_step": "새 단계 추가...",
    "task.add_step": "단계 추가",
    "task.due_date": "마감일",
    "task.importance": "중요도",
    "task.edit_details": "세부 정보 편집",
    "task.no_subtasks": "하위 작업 없음",
    "calendar.no_tasks": "이 날의 작업 없음",
    "calendar.quick_add": "빠른 작업 추가...",
    "profile.title": "계정",
    "profile.cloud_sync": "클라우드 동기화",
    "profile.synced": "동기화됨",
    "profile.local": "로컬 전용",
    "profile.auth_error": "인증 오류",
    "profile.plan_pro": "프로 플랜",
    "profile.plan_free": "무료 플랜",
    "profile.plan_active": "활성",
    "profile.plan_upgrade_hint": "동기화를 위해 업그레이드",
    "profile.upgrade": "업그레이드",
    "profile.sign_out": "로그아웃",
    "profile.create_account": "계정 만들기",
    "profile.sign_in": "로그인",
    "profile.google": "Google로 계속",
    "profile.or_email": "또는 이메일로",
    "profile.email_placeholder": "이메일 주소",
    "profile.password_placeholder": "비밀번호",
    "profile.sign_up": "가입하기",
    "profile.have_account": "이미 계정이 있으신가요?",
    "profile.no_account": "계정이 없으신가요?",
    "profile.exit_hub": "허브로 돌아가기",
    "journal.title": "저널",
    "journal.quick_notes": "빠른 메모",
    "journal.no_notes": "메모 없음",
    "journal.search": "메모 검색...",
    "journal.not_found": "메모를 찾을 수 없음",
    "journal.unsaved": "저장되지 않음",
    "journal.saved": "저장됨",
    "journal.title_placeholder": "제목",
    "journal.content_placeholder": "글쓰기 시작...",
    "journal.select": "메모 선택",
    "journal.create_prompt": "목록에서 메모를 선택하거나 새로 만드세요.",
    "hub.welcome": "환영합니다",
    "hub.subtitle": "무엇을 하시겠습니까?",
    "hub.app.focus": "데일리 플래너 & 타이머",
    "hub.app.brainstorm": "자유로운 아이디어",
    "hub.app.vault": "보안 저장소",
    "hub.app.tools": "유틸리티",
    "hub.soon": "준비 중",
    "map.zoom_in": "확대",
    "map.zoom_out": "축소",
    "map.reset": "초기화"
  }
};

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const ThemeProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('loffeeflow_theme') as Theme) || 'light');
  const [uiSize, setUiSizeState] = useState<UISize>(() => (localStorage.getItem('loffeeflow_size') as UISize) || 'medium');
  const [snapEnabled, setSnapEnabled] = useState<boolean>(() => localStorage.getItem('loffeeflow_snap') !== 'false');
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem('loffeeflow_lang') as Language) || 'en');
  const [autoHideControls, setAutoHideControls] = useState<boolean>(() => localStorage.getItem('loffeeflow_autohide') === 'true');
  const [autoHideDuration, setAutoHideDurationState] = useState<number>(() => parseInt(localStorage.getItem('loffeeflow_autohide_duration') || '5000', 10));
  const [autoDeleteOverdue, setAutoDeleteOverdue] = useState<boolean>(() => localStorage.getItem('loffeeflow_autodelete') === 'true');

  useEffect(() => {
    localStorage.setItem('loffeeflow_theme', theme);
    document.documentElement.classList.toggle('dark', theme === 'dark');
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('loffeeflow_size', uiSize);
    document.documentElement.style.fontSize = uiSize === 'small' ? '90%' : uiSize === 'large' ? '112.5%' : '100%';
  }, [uiSize]);

  useEffect(() => { localStorage.setItem('loffeeflow_lang', language); document.documentElement.lang = language; }, [language]);

  useEffect(() => {
    localStorage.setItem('loffeeflow_autodelete', String(autoDeleteOverdue));
  }, [autoDeleteOverdue]);

  const t = (key: string): string => translations[language][key] || translations['en'][key] || key;

  return (
    <ThemeContext.Provider value={{ 
        theme, uiSize, snapEnabled, language, autoHideControls, autoHideDuration, autoDeleteOverdue,
        toggleTheme: () => setTheme(prev => prev === 'light' ? 'dark' : 'light'),
        setUiSize: setUiSizeState,
        toggleSnap: () => setSnapEnabled(p => !p),
        setLanguage: setLanguageState,
        toggleAutoHide: () => setAutoHideControls(p => !p),
        toggleAutoDeleteOverdue: () => setAutoDeleteOverdue(p => !p),
        setAutoHideDuration: setAutoHideDurationState, 
        t
    }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) throw new Error('useTheme error');
  return context;
};
